### ISSUE TITLE
Not able to spin up boostminer

### ISSUE THREAD

**Issue by mak1986** [pow-co/boostpow-cpuminer-nodejs#17]
I'm using Ubuntu 20.04.2 LTS

```
mak@mak-desktop:~$ boostminer --privatekey xxx --address xxx start
/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/node_modules/nconf/lib/nconf/provider.js:364
    throw new Error('Missing required keys: ' + missing.join(', '));
    ^

Error: Missing required keys: miner_private_key
    at exports.Provider.Provider.required (/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/node_modules/nconf/lib/nconf/provider.js:364:11)
    at Object.<anonymous> (/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/dist/config.js:40:7)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/dist/miner.js:56:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)

Node.js v17.9.1
```

I also tried

```
mak@mak-desktop:~$ BOOSTMINER_PRIVATE_KEY=xxx BOOSTMINER_ADDRESS=xxx boostminer start
/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/node_modules/nconf/lib/nconf/provider.js:364
    throw new Error('Missing required keys: ' + missing.join(', '));
    ^

Error: Missing required keys: miner_private_key
    at exports.Provider.Provider.required (/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/node_modules/nconf/lib/nconf/provider.js:364:11)
    at Object.<anonymous> (/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/dist/config.js:40:7)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mak/.nvm/versions/node/v17.9.1/lib/node_modules/boostminer/dist/miner.js:56:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)

Node.js v17.9.1
```

**Comment by owenkellogg** [comment]
Hello @mak1986 please try github.com/pow-co/boostpow-cpuminer
